# Generated by Django 2.2.2 on 2019-06-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiveRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_home', models.CharField(max_length=100)),
                ('room_id', models.IntegerField()),
                ('room_name', models.TextField()),
                ('user_id', models.IntegerField()),
                ('user_name', models.TextField()),
                ('room_kind', models.CharField(max_length=20)),
                ('room_olnum', models.IntegerField()),
                ('room_usertag', models.TextField()),
            ],
        ),
    ]
